# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sample.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from db_ops import insert

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.roll_no = QtWidgets.QLabel(self.centralwidget)
        self.roll_no.setGeometry(QtCore.QRect(70, 70, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        self.roll_no.setFont(font)
        self.roll_no.setObjectName("roll_no")
        self.roll_nolineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.roll_nolineEdit.setGeometry(QtCore.QRect(370, 80, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.roll_nolineEdit.setFont(font)
        self.roll_nolineEdit.setObjectName("roll_nolineEdit")
        self.Game_name = QtWidgets.QLabel(self.centralwidget)
        self.Game_name.setGeometry(QtCore.QRect(70, 150, 271, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        self.Game_name.setFont(font)
        self.Game_name.setObjectName("Game_name")
        self.Game_name_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.Game_name_lineEdit.setGeometry(QtCore.QRect(370, 160, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Game_name_lineEdit.setFont(font)
        self.Game_name_lineEdit.setObjectName("Game_name_lineEdit")
        self.Submit_button = QtWidgets.QPushButton(self.centralwidget)
        self.Submit_button.setGeometry(QtCore.QRect(270, 260, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Unicode MS")
        font.setPointSize(14)
        self.Submit_button.setFont(font)
        self.Submit_button.setStyleSheet("QPushButton#Submit_button { background-color: rgb(104, 175, 157)}")
        self.Submit_button.setObjectName("Submit_button")
        self.Output_label = QtWidgets.QLabel(self.centralwidget)
        self.Output_label.setGeometry(QtCore.QRect(180, 390, 391, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Output_label.setFont(font)
        self.Output_label.setStyleSheet("")
        self.Output_label.setText("")
        self.Output_label.setObjectName("Output_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def get_data(self):
        roll_no = self.roll_nolineEdit.text()
        game_name = self.Game_name_lineEdit.text()
        insert((roll_no, game_name),"activity")
        self.Output_label.setText("Inserted")
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.roll_no.setText(_translate("MainWindow", "Enter the Roll_no"))
        self.Game_name.setText(_translate("MainWindow", "Enter the Game_name"))
        self.Submit_button.setText(_translate("MainWindow", "Submit"))
        self.Submit_button.clicked.connect(self.get_data)
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
