# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Upper_lower.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 711)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.input_text = QtWidgets.QTextEdit(self.centralwidget)
        self.input_text.setGeometry(QtCore.QRect(130, 70, 531, 171))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.input_text.setFont(font)
        self.input_text.setStyleSheet("")
        self.input_text.setObjectName("input_text")
        self.SubmitButton = QtWidgets.QPushButton(self.centralwidget)
        self.SubmitButton.setGeometry(QtCore.QRect(280, 280, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(14)
        self.SubmitButton.setFont(font)
        self.SubmitButton.setStyleSheet("background-color: rgb(189, 255, 89);\n"
"color: rgb(85, 0, 0);")
        self.SubmitButton.setObjectName("SubmitButton")
        self.Output_text = QtWidgets.QTextEdit(self.centralwidget)
        self.Output_text.setGeometry(QtCore.QRect(140, 390, 531, 171))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.Output_text.setFont(font)
        self.Output_text.setStyleSheet("")
        self.Output_text.setObjectName("Output_text")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
    def action(self):
        data = self.input_text.toPlainText()
        data = data.upper()
        self.Output_text.setPlainText(data)
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SubmitButton.setToolTip(_translate("MainWindow", "Change the Text"))
        self.SubmitButton.setText(_translate("MainWindow", "Submit"))
        self.SubmitButton.clicked.connect(self.action)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
