# Generated by Django 3.2.9 on 2021-12-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_id', models.IntegerField()),
                ('st_name', models.CharField(max_length=100)),
                ('st_mail', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('st_id', 'subject')},
            },
        ),
    ]
