# Generated by Django 3.2.9 on 2021-12-10 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attendence', '0002_masterdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark_Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('time1', models.IntegerField()),
                ('ip_address', models.CharField(max_length=100)),
                ('date1', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='S_Id', to='Attendence.masterdata')),
            ],
            options={
                'unique_together': {('ID', 'date1'), ('date1', 'ip_address')},
            },
        ),
    ]
