# Generated by Django 3.2.9 on 2021-12-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendence', '0003_mark_attendence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark_attendence',
            name='platform',
            field=models.CharField(max_length=200),
        ),
    ]
